version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - symfony-network

  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    container_name: php-container
    volumes:
      - ./app:/var/www/project
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - symfony-network

  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    networks:
      - symfony-network

networks:
  symfony-network:
    driver: bridge

volumes:
  pgdata: